### ISSUE TITLE
suggested offlineimap migration script might corrupt messages

### ISSUE THREAD

**Issue by anarcat** [gares/syncmaildir#1]
Hi!

i couldn't help but notice that the suggested way of removing the `X-Offlineimap` markers might corrupt existing messages if they happen to have a line that starts with that string elsewhere in the message, for example in the body or in an attachment. Shouldn't there be something that keeps the modification restricted to the headers of files?

**Comment by anarcat** [comment]
i ended up rolling my own script here:

https://gitlab.com/anarcat/scripts/blob/master/strip_header

it seems to work more reliably than the `sed` pattern.

**Comment by gares** [comment]
Thanks! If you submit a PR with your script I'd gladly merge it. Or you prefer to keep the script in your repo?

**Comment by anarcat** [comment]
No, I'd be happy to contribute this back. How should the thing be named?

**Comment by gares** [comment]
I would call it `misc/strip-X-OfflineIMAP` and link it from the README.md (with little doc) instead of having the `sed` line. Also the docstring of your code needs to remove the mention to `sed`, since it is going away!

**Comment by anarcat** [comment]
i think i'll stick with strip-header because it is possible to strip other headers with it, if you don't mind. i'll tweak the `sed` reference to take into account it is going away as well.

**Comment by anarcat** [comment]
@gares #3 available for your review! :)
