### ISSUE TITLE
support xdelta3 (which is seemingly incompatible to xdelta)

### ISSUE THREAD

**Issue by manuelsteiner** [gares/syncmaildir#14]
Hi,

I just spent a few hours trying to get syncmaildir to run properly. Apparently there is a substantial differerence betwwen `xdelta` and `xdelta3`. Apart from different command line arguments, they also seem to be incompatible.
Since Debian still ships with the old xdata, this is fine but other distributions, such as Fedora, only come with the newer `xdata3` and calling `xdelta` just invokes `xdelta3` as well. Syncing betwwen different distributions can be a bit of a hassle because of that.

I was able to patch the source to use the new version in `smd-client` and `smd-server` and the sync as well as successive re=syncs were successful. 

I was pondering about submitting a pull request. I am unsure however if both versions should be supported and what the best course of action would be to set the preferred version (in a config file?, determine at runtime? probably a bad idea since using v1 and v3 for sync seemingly doesn't work).

Any comments would be appreciated.

**Comment by gares** [comment]
I've just checked and debian also ships xdelta3 (in the package xdelta3).

I don't know the differences introduced in xdelta3, but I imagine we could just switch to that, I really mean call the binary `xdelta3` with appropriate flags. At least on debian `xdelta3` always refers to version 3 (`xdelta` also seem to refer to version 1, but I guess fedora does differently). Does `xdelta3` exist on fedora?

**Comment by gares** [comment]
Or the binary is only called `xdelta`?

**Comment by manuelsteiner** [comment]
Fedora e.g. has the `xdelta3` binary too but the `xdelta` just symlinks to `xdelta3`. So just supporting xdelta3 would be fine for Fedora at least. I am not sure about other systems though.

**Comment by manuelsteiner** [comment]
For reference, this is how I call xdelta3.
smd-client: `rc = os.execute(XDELTA..' -d -s '..dbfile..' '..xdelta..'  '..newdb)`
smd-server: `rc = os.execute(XDELTA..' -e -s '..dbfile..' '..newdb..' '..xdelta)`

**Comment by gares** [comment]
thanks! It would be awesome if you could submit a PR, my time to work on smd is very limited these days.

**Comment by manuelsteiner** [comment]
Will do in the next few days.

**Comment by manuelsteiner** [comment]
Submitted, also fixed lua env replacement in the Makefile while I was at it. Hope that's ok.

**Comment by manuelsteiner** [comment]
implemented in #15
